/**
 * Season points, the pure half (node --test loads this directly; relative imports only).
 *
 * Points are reputation for launching and trading, recomputed from scratch from the chain index. The rules reward what
 * costs real money or reputation to fake and nothing that is free to repeat:
 *
 *   Creator (per token the wallet launched; any token, only activity inside the season counts)
 *     - each outside buyer whose first buy was in the season and still holds after 24 h: 30 if their wallet is
 *       points-eligible (X-verified, account age and followers), else 5; the eligible holder needs ≥ $1 held,
 *       the other ≥ $5; still holding at day 7 adds half again
 *     - 10 per $1 of trading fees generated by outside trades in the season (the fee exists whoever it is paid to)
 *     - 100 once if the token is a week old, has ≥ 10 outside holders and an outside trade in the last day
 *     - the token scores 0 if, during the season, the creator sold half or more of what they ever bought of it
 *     - of the tokens a wallet launched on one UTC day, only the best 3 count
 *   Scout (traders)
 *     - 100 for being one of the first 25 outside buyers (first buy ≥ $5, in the season) of a token that has reached
 *       50 outside holders; 50 more while still holding
 *     - 5 per token bought (≥ $5, in the season) and still held 24 h later; at most 20 tokens per UTC day
 *     - 10 per $1 of fees paid on other people's tokens that have ≥ 20 outside holders; at most 200 per token per day
 *
 * "Outside" = not the launcher, not a fee recipient, not a protocol address, not a wallet that got the token by
 * transfer from the launcher or a recipient, not a wallet an admin kept off points, and never a buy inside the
 * sniper window (launch block + SNIPER_BLOCKS). Trades under $5 earn nothing.
 */

export const RULES = {
  sniperBlocks: 3,
  minTradeUsd: 5,
  verifiedHolder: 30,
  verifiedHolderMinUsd: 1,
  holder: 5,
  holderMinUsd: 5,
  day7Bonus: 0.5,
  creatorFeePointsPerUsd: 10,
  alive: 100,
  aliveMinHolders: 10,
  aliveAgeMs: 7 * 86_400_000,
  bestTokensPerDay: 3,
  early: 100,
  earlyStillHolding: 50,
  earlyFirstBuyers: 25,
  earlyHoldersTarget: 50,
  hold: 5,
  holdTokensPerDay: 20,
  scoutFeePointsPerUsd: 10,
  scoutFeeCapPerTokenDay: 200,
  scoutFeeMinHolders: 20,
} as const;

const DAY = 86_400_000;

export type ScoreLaunch = {
  key: string; // chain:token
  launcher: string;
  recipients: readonly string[];
  launchBlock: number;
  launchTime: number; // ms
  lpFee: number; // pips (10_000 = 1%)
  quoteDecimals: number;
  quoteUsd: number | null; // USD per whole quote unit; null = unpriced (no USD-gated points)
  tokenUsd: number | null; // USD per whole token now
};
export type ScoreSwap = { key: string; trader: string; isBuy: boolean; quoteRaw: bigint; tokenRaw: bigint; block: number; time: number };
/** A wallet's first buy of a token, all-time (rank among outside buyers decides "early"). */
export type FirstBuy = { key: string; wallet: string; block: number; time: number; quoteRaw: bigint };

export type ScoreInput = {
  seasonStart: number;
  seasonEnd: number;
  now: number;
  launches: readonly ScoreLaunch[];
  /** swaps inside the season, any order */
  swaps: readonly ScoreSwap[];
  firstBuys: readonly FirstBuy[];
  /** current balances (raw, 18 decimals) of the tokens in scope */
  holders: readonly { key: string; wallet: string; balanceRaw: bigint }[];
  /** the launcher's all-time bought amount (raw) per token */
  launcherBought: ReadonlyMap<string, bigint>;
  /** per token: wallets that received it by transfer from the launcher or a fee recipient */
  linked: ReadonlyMap<string, ReadonlySet<string>>;
  /** protocol addresses (pool manager, routers, locker, factory, zero, dead) */
  system: ReadonlySet<string>;
  eligible: ReadonlySet<string>;
  /** kept off points by an admin: never points, never counted as anyone's outside holder or buyer */
  flagged: ReadonlySet<string>;
  /** the most outside holders each token had earlier this season */
  maxOutsideBefore: ReadonlyMap<string, number>;
};

export type CreatorBreakdown = { tokens: number; verifiedHolders: number; holders: number; feesUsd: number; alive: number; dumped: number };
export type ScoutBreakdown = { early: number; holds: number; feesUsd: number };
export type WalletScore = { wallet: string; creator: number; scout: number; total: number; creatorWhy: CreatorBreakdown; scoutWhy: ScoutBreakdown };
export type ScoreResult = { wallets: Map<string, WalletScore>; maxOutside: Map<string, number> };

const units = (raw: bigint, decimals: number) => Number(raw) / 10 ** decimals;
const utcDay = (ms: number) => Math.floor(ms / DAY);

export function scoreSeason(input: ScoreInput): ScoreResult {
  const end = Math.min(input.now, input.seasonEnd);
  const launches = new Map(input.launches.map((l) => [l.key, l]));
  const wallets = new Map<string, WalletScore>();
  const get = (w: string) => {
    let s = wallets.get(w);
    if (!s) {
      s = { wallet: w, creator: 0, scout: 0, total: 0, creatorWhy: { tokens: 0, verifiedHolders: 0, holders: 0, feesUsd: 0, alive: 0, dumped: 0 }, scoutWhy: { early: 0, holds: 0, feesUsd: 0 } };
      wallets.set(w, s);
    }
    return s;
  };

  const insider = (l: ScoreLaunch, w: string) => w === l.launcher || l.recipients.includes(w) || input.system.has(w) || input.flagged.has(w) || (input.linked.get(l.key)?.has(w) ?? false);
  const usdOfQuote = (l: ScoreLaunch, raw: bigint) => (l.quoteUsd === null ? null : units(raw, l.quoteDecimals) * l.quoteUsd);
  const usdOfTokens = (l: ScoreLaunch, raw: bigint) => (l.tokenUsd === null ? null : units(raw, 18) * l.tokenUsd);
  const inSeason = (t: number) => t >= input.seasonStart && t < end;

  // first buys: the outside buyers of each token in buy order (sniper-window buys never count)
  const firstByToken = new Map<string, FirstBuy[]>();
  for (const f of input.firstBuys) {
    const l = launches.get(f.key);
    if (!l || insider(l, f.wallet) || f.block <= l.launchBlock + RULES.sniperBlocks) continue;
    const list = firstByToken.get(f.key) ?? [];
    list.push(f);
    firstByToken.set(f.key, list);
  }
  for (const list of firstByToken.values()) list.sort((a, b) => a.block - b.block || a.time - b.time);
  const firstOf = new Map<string, FirstBuy>();
  for (const [key, list] of firstByToken) for (const f of list) firstOf.set(`${key}|${f.wallet}`, f);

  // current outside holders per token
  const balance = new Map<string, bigint>();
  const outsideHolders = new Map<string, string[]>();
  for (const h of input.holders) {
    if (h.balanceRaw <= 0n) continue;
    balance.set(`${h.key}|${h.wallet}`, h.balanceRaw);
    const l = launches.get(h.key);
    if (!l || insider(l, h.wallet)) continue;
    const list = outsideHolders.get(h.key) ?? [];
    list.push(h.wallet);
    outsideHolders.set(h.key, list);
  }
  const maxOutside = new Map<string, number>();
  for (const l of input.launches) maxOutside.set(l.key, Math.max(input.maxOutsideBefore.get(l.key) ?? 0, outsideHolders.get(l.key)?.length ?? 0));

  // the season's outside swaps, and what each token's creator sold
  const outsideSwaps: ScoreSwap[] = [];
  const lastOutsideTrade = new Map<string, number>();
  const creatorSold = new Map<string, bigint>();
  for (const s of input.swaps) {
    const l = launches.get(s.key);
    if (!l || !inSeason(s.time)) continue;
    if (s.trader === l.launcher && !s.isBuy) creatorSold.set(s.key, (creatorSold.get(s.key) ?? 0n) + s.tokenRaw);
    if (insider(l, s.trader) || s.block <= l.launchBlock + RULES.sniperBlocks) continue;
    outsideSwaps.push(s);
    lastOutsideTrade.set(s.key, Math.max(lastOutsideTrade.get(s.key) ?? 0, s.time));
  }

  // ── creator points, per token, then the best 3 per launcher per launch day ──
  type TokenCreator = { l: ScoreLaunch; points: number; verifiedHolders: number; holders: number; feesUsd: number; alive: number; dumped: boolean };
  const perToken = new Map<string, TokenCreator>();
  const ensure = (l: ScoreLaunch) => {
    let t = perToken.get(l.key);
    if (!t) {
      t = { l, points: 0, verifiedHolders: 0, holders: 0, feesUsd: 0, alive: 0, dumped: false };
      perToken.set(l.key, t);
    }
    return t;
  };
  for (const [key, holdersList] of outsideHolders) {
    const l = launches.get(key)!;
    for (const w of holdersList) {
      const f = firstOf.get(`${key}|${w}`);
      if (!f || !inSeason(f.time) || end - f.time < DAY) continue; // gained this season, held a day
      const eligible = input.eligible.has(w);
      const value = usdOfTokens(l, balance.get(`${key}|${w}`) ?? 0n);
      if (value !== null && value < (eligible ? RULES.verifiedHolderMinUsd : RULES.holderMinUsd)) continue;
      const base = eligible ? RULES.verifiedHolder : RULES.holder;
      const t = ensure(l);
      t.points += base * (end - f.time >= 7 * DAY ? 1 + RULES.day7Bonus : 1);
      if (eligible) t.verifiedHolders++;
      else t.holders++;
    }
  }
  for (const s of outsideSwaps) {
    const l = launches.get(s.key)!;
    const usd = usdOfQuote(l, s.quoteRaw);
    if (usd === null) continue;
    const fee = (usd * l.lpFee) / 1_000_000;
    if (fee <= 0) continue;
    const t = ensure(l);
    t.feesUsd += fee;
    t.points += fee * RULES.creatorFeePointsPerUsd;
  }
  for (const l of input.launches) {
    if (end - l.launchTime < RULES.aliveAgeMs) continue;
    if ((outsideHolders.get(l.key)?.length ?? 0) < RULES.aliveMinHolders) continue;
    if (end - (lastOutsideTrade.get(l.key) ?? 0) > DAY) continue;
    const t = ensure(l);
    t.alive = 1;
    t.points += RULES.alive;
  }
  for (const t of perToken.values()) {
    const bought = input.launcherBought.get(t.l.key) ?? 0n;
    const sold = creatorSold.get(t.l.key) ?? 0n;
    // only against what the creator bought: selling the token-side fees the pool paid them is not a dump
    if (bought > 0n && sold * 2n >= bought) {
      t.dumped = true;
      t.points = 0;
    }
  }
  const byLauncherDay = new Map<string, TokenCreator[]>();
  for (const t of perToken.values()) {
    const k = `${t.l.launcher}|${utcDay(t.l.launchTime)}`;
    const list = byLauncherDay.get(k) ?? [];
    list.push(t);
    byLauncherDay.set(k, list);
  }
  for (const list of byLauncherDay.values()) {
    list.sort((a, b) => b.points - a.points);
    list.forEach((t, i) => {
      const w = t.l.launcher;
      if (input.flagged.has(w)) return;
      const s = get(w);
      if (t.dumped) s.creatorWhy.dumped++;
      if (i >= RULES.bestTokensPerDay || t.points <= 0) return;
      s.creator += t.points;
      s.creatorWhy.tokens++;
      s.creatorWhy.verifiedHolders += t.verifiedHolders;
      s.creatorWhy.holders += t.holders;
      s.creatorWhy.feesUsd += t.feesUsd;
      s.creatorWhy.alive += t.alive;
    });
  }

  // ── scout points ──
  for (const [key, list] of firstByToken) {
    const l = launches.get(key)!;
    if ((maxOutside.get(key) ?? 0) < RULES.earlyHoldersTarget) continue;
    list.slice(0, RULES.earlyFirstBuyers).forEach((f) => {
      if (!inSeason(f.time)) return;
      const usd = usdOfQuote(l, f.quoteRaw);
      if (usd !== null && usd < RULES.minTradeUsd) return;
      const s = get(f.wallet);
      s.scout += RULES.early + ((balance.get(`${key}|${f.wallet}`) ?? 0n) > 0n ? RULES.earlyStillHolding : 0);
      s.scoutWhy.early++;
    });
  }
  // holds: the first in-season buy of a token (≥ $5), still held a day later; at most 20 tokens per buy day
  const holdsPerDay = new Map<string, number>();
  const firstSeasonBuy = new Map<string, ScoreSwap>();
  for (const s of outsideSwaps) {
    if (!s.isBuy) continue;
    const k = `${s.key}|${s.trader}`;
    const cur = firstSeasonBuy.get(k);
    if (!cur || s.time < cur.time) firstSeasonBuy.set(k, s);
  }
  for (const s of [...firstSeasonBuy.values()].sort((a, b) => a.time - b.time)) {
    const l = launches.get(s.key)!;
    const usd = usdOfQuote(l, s.quoteRaw);
    if (usd !== null && usd < RULES.minTradeUsd) continue;
    if (end - s.time < DAY || (balance.get(`${s.key}|${s.trader}`) ?? 0n) <= 0n) continue;
    const dayKey = `${s.trader}|${utcDay(s.time)}`;
    const n = holdsPerDay.get(dayKey) ?? 0;
    if (n >= RULES.holdTokensPerDay) continue;
    holdsPerDay.set(dayKey, n + 1);
    const w = get(s.trader);
    w.scout += RULES.hold;
    w.scoutWhy.holds++;
  }
  // fees paid on other people's real tokens, capped per token per day
  const feeCap = new Map<string, number>();
  for (const s of outsideSwaps) {
    const l = launches.get(s.key)!;
    if ((maxOutside.get(s.key) ?? 0) < RULES.scoutFeeMinHolders) continue;
    const usd = usdOfQuote(l, s.quoteRaw);
    if (usd === null || usd < RULES.minTradeUsd) continue;
    const fee = (usd * l.lpFee) / 1_000_000;
    if (fee <= 0) continue;
    const capKey = `${s.trader}|${s.key}|${utcDay(s.time)}`;
    const used = feeCap.get(capKey) ?? 0;
    const pts = Math.min(fee * RULES.scoutFeePointsPerUsd, RULES.scoutFeeCapPerTokenDay - used);
    if (pts <= 0) continue;
    feeCap.set(capKey, used + pts);
    const w = get(s.trader);
    w.scout += pts;
    w.scoutWhy.feesUsd += fee;
  }

  for (const w of [...wallets.keys()]) {
    const s = wallets.get(w)!;
    if (input.flagged.has(w)) {
      wallets.delete(w);
      continue;
    }
    s.creator = Math.round(s.creator);
    s.scout = Math.round(s.scout);
    s.total = s.creator + s.scout;
    s.creatorWhy.feesUsd = Math.round(s.creatorWhy.feesUsd * 100) / 100;
    s.scoutWhy.feesUsd = Math.round(s.scoutWhy.feesUsd * 100) / 100;
    if (s.total <= 0 && s.creatorWhy.dumped === 0) wallets.delete(w);
  }
  return { wallets, maxOutside };
}

/** Ranks among eligible wallets (1 = best); ties share a rank. */
export function rankBy(scores: readonly WalletScore[], field: "creator" | "scout", eligible: ReadonlySet<string>): Map<string, number> {
  const list = scores.filter((s) => eligible.has(s.wallet) && s[field] > 0).sort((a, b) => b[field] - a[field] || a.wallet.localeCompare(b.wallet));
  const out = new Map<string, number>();
  let rank = 0;
  let prev = Number.NaN;
  list.forEach((s, i) => {
    if (s[field] !== prev) {
      rank = i + 1;
      prev = s[field];
    }
    out.set(s.wallet, rank);
  });
  return out;
}

/** One line of "why" for a leaderboard row, from the breakdown. */
export function whyLine(board: "creator" | "scout", s: Pick<WalletScore, "creatorWhy" | "scoutWhy">): string {
  const parts: string[] = [];
  const usd = (n: number) => `$${n >= 100 ? Math.round(n).toLocaleString("en-US") : n.toFixed(2)}`;
  if (board === "creator") {
    const c = s.creatorWhy;
    if (c.verifiedHolders) parts.push(`${c.verifiedHolders} verified holder${c.verifiedHolders === 1 ? "" : "s"}`);
    if (c.holders) parts.push(`${c.holders} holder${c.holders === 1 ? "" : "s"}`);
    if (c.feesUsd >= 0.01) parts.push(`${usd(c.feesUsd)} fees`);
    if (c.alive) parts.push(`${c.alive} alive at day 7`);
  } else {
    const c = s.scoutWhy;
    if (c.early) parts.push(`early on ${c.early} token${c.early === 1 ? "" : "s"}`);
    if (c.holds) parts.push(`${c.holds} held a day+`);
    if (c.feesUsd >= 0.01) parts.push(`${usd(c.feesUsd)} fees paid`);
  }
  return parts.join(" · ");
}
